# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61pi/common.proto\x12\x03\x61pi\"\x8a\x04\n\x06\x46\x61mily\x12\x1c\n\x03\x61\x66i\x18\x01 \x01(\x0e\x32\x0f.api.Family.Afi\x12\x1e\n\x04safi\x18\x02 \x01(\x0e\x32\x10.api.Family.Safi\"b\n\x03\x41\x66i\x12\x13\n\x0f\x41\x46I_UNSPECIFIED\x10\x00\x12\n\n\x06\x41\x46I_IP\x10\x01\x12\x0b\n\x07\x41\x46I_IP6\x10\x02\x12\r\n\tAFI_L2VPN\x10\x19\x12\x0c\n\x06\x41\x46I_LS\x10\x84\x80\x01\x12\x10\n\nAFI_OPAQUE\x10\x8d\x80\x01\"\xdd\x02\n\x04Safi\x12\x14\n\x10SAFI_UNSPECIFIED\x10\x00\x12\x10\n\x0cSAFI_UNICAST\x10\x01\x12\x12\n\x0eSAFI_MULTICAST\x10\x02\x12\x13\n\x0fSAFI_MPLS_LABEL\x10\x04\x12\x16\n\x12SAFI_ENCAPSULATION\x10\x07\x12\r\n\tSAFI_VPLS\x10\x41\x12\r\n\tSAFI_EVPN\x10\x46\x12\x0b\n\x07SAFI_LS\x10G\x12\x12\n\x0eSAFI_SR_POLICY\x10I\x12\x0c\n\x08SAFI_MUP\x10U\x12\x12\n\rSAFI_MPLS_VPN\x10\x80\x01\x12\x1c\n\x17SAFI_MPLS_VPN_MULTICAST\x10\x81\x01\x12\"\n\x1dSAFI_ROUTE_TARGET_CONSTRAINTS\x10\x84\x01\x12\x1b\n\x16SAFI_FLOW_SPEC_UNICAST\x10\x85\x01\x12\x17\n\x12SAFI_FLOW_SPEC_VPN\x10\x86\x01\x12\x13\n\x0eSAFI_KEY_VALUE\x10\xf1\x01\"@\n\x1dRouteDistinguisherTwoOctetASN\x12\r\n\x05\x61\x64min\x18\x01 \x01(\r\x12\x10\n\x08\x61ssigned\x18\x02 \x01(\r\">\n\x1bRouteDistinguisherIPAddress\x12\r\n\x05\x61\x64min\x18\x01 \x01(\t\x12\x10\n\x08\x61ssigned\x18\x02 \x01(\r\"A\n\x1eRouteDistinguisherFourOctetASN\x12\r\n\x05\x61\x64min\x18\x01 \x01(\r\x12\x10\n\x08\x61ssigned\x18\x02 \x01(\r\"\xce\x01\n\x12RouteDistinguisher\x12;\n\rtwo_octet_asn\x18\x01 \x01(\x0b\x32\".api.RouteDistinguisherTwoOctetASNH\x00\x12\x36\n\nip_address\x18\x02 \x01(\x0b\x32 .api.RouteDistinguisherIPAddressH\x00\x12=\n\x0e\x66our_octet_asn\x18\x03 \x01(\x0b\x32#.api.RouteDistinguisherFourOctetASNH\x00\x42\x04\n\x02rdB\"Z github.com/osrg/gobgp/v4/api;apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z github.com/osrg/gobgp/v4/api;api'
  _globals['_FAMILY']._serialized_start=26
  _globals['_FAMILY']._serialized_end=548
  _globals['_FAMILY_AFI']._serialized_start=98
  _globals['_FAMILY_AFI']._serialized_end=196
  _globals['_FAMILY_SAFI']._serialized_start=199
  _globals['_FAMILY_SAFI']._serialized_end=548
  _globals['_ROUTEDISTINGUISHERTWOOCTETASN']._serialized_start=550
  _globals['_ROUTEDISTINGUISHERTWOOCTETASN']._serialized_end=614
  _globals['_ROUTEDISTINGUISHERIPADDRESS']._serialized_start=616
  _globals['_ROUTEDISTINGUISHERIPADDRESS']._serialized_end=678
  _globals['_ROUTEDISTINGUISHERFOUROCTETASN']._serialized_start=680
  _globals['_ROUTEDISTINGUISHERFOUROCTETASN']._serialized_end=745
  _globals['_ROUTEDISTINGUISHER']._serialized_start=748
  _globals['_ROUTEDISTINGUISHER']._serialized_end=954
# @@protoc_insertion_point(module_scope)
